# Generated by Django 5.2.11 on 2026-02-23 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=8)),
                ('ram', models.IntegerField(default=16)),
                ('swap', models.IntegerField(default=16)),
                ('cores', models.IntegerField(default=1)),
                ('bandwidth', models.IntegerField(default=1024)),
                ('cpu_units', models.IntegerField(default=1024)),
                ('cpu_limit', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('ipv6_ips', models.IntegerField(default=0)),
                ('ipv4_ips', models.IntegerField(default=0)),
                ('internal_ips', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('lxc', 'LXC'), ('kvm', 'KVM')], default='lxc', max_length=255)),
                ('file', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=8)),
                ('ram', models.IntegerField(default=16)),
                ('swap', models.IntegerField(default=16)),
                ('cores', models.IntegerField(default=1)),
                ('bandwidth', models.IntegerField(default=1024)),
                ('cpu_units', models.IntegerField(default=1024)),
                ('cpu_limit', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('ipv6_ips', models.IntegerField(default=0)),
                ('ipv4_ips', models.IntegerField(default=0)),
                ('internal_ips', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inveterate.cluster')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='IPPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('ipv4', 'IPv4'), ('ipv6', 'IPv6')], default='ipv4', max_length=255)),
                ('network', models.GenericIPAddressField()),
                ('mask', models.IntegerField()),
                ('gateway', models.GenericIPAddressField()),
                ('internal', models.BooleanField(default=False)),
                ('interface', models.CharField(default='vmbr0', max_length=255)),
                ('dns', models.GenericIPAddressField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nodes', models.ManyToManyField(to='inveterate.node')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='NodeDisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('primary', models.BooleanField(default=True)),
                ('shared', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_disk', to='inveterate.node')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inveterate.node')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inveterate.plan')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('destroyed', 'Destroyed'), ('suspended', 'Suspended'), ('error', 'Error'), ('past_due', 'Past Due')], default='pending', max_length=255)),
                ('status_msg', models.CharField(blank=True, max_length=255, null=True)),
                ('hostname', models.CharField(max_length=255)),
                ('machine_id', models.IntegerField(blank=True, null=True)),
                ('bw_usage', models.BigIntegerField(default=0)),
                ('bw_banked', models.BigIntegerField(default=0)),
                ('bw_stale', models.BigIntegerField(default=0)),
                ('bw_system_tick', models.IntegerField(default=0)),
                ('bw_renewal_dtm', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='inveterate.node')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ServiceNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_id', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_network', to='inveterate.service')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.GenericIPAddressField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inveterate.ippool')),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inveterate.servicenetwork')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=8)),
                ('ram', models.IntegerField(default=16)),
                ('swap', models.IntegerField(default=16)),
                ('cores', models.IntegerField(default=1)),
                ('bandwidth', models.IntegerField(default=1024)),
                ('cpu_units', models.IntegerField(default=1024)),
                ('cpu_limit', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('ipv6_ips', models.IntegerField(default=0)),
                ('ipv4_ips', models.IntegerField(default=0)),
                ('internal_ips', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=255)),
                ('type', models.CharField(choices=[('lxc', 'LXC'), ('kvm', 'KVM')], max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inveterate.nodedisk')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inveterate.template')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='service_plan',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service', to='inveterate.serviceplan'),
        ),
        migrations.AddConstraint(
            model_name='nodedisk',
            constraint=models.UniqueConstraint(condition=models.Q(('primary', True)), fields=('node', 'primary'), name='unique_primary_per_node'),
        ),
    ]
