# Generated by Django 5.1.3 on 2025-03-23 15:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='DashboardSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_count', models.IntegerField()),
                ('plan_count', models.IntegerField()),
                ('ip_count', models.IntegerField()),
                ('template_count', models.IntegerField()),
                ('service_count', models.IntegerField()),
                ('node_count', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=8)),
                ('ram', models.IntegerField(default=16)),
                ('swap', models.IntegerField(default=16)),
                ('cores', models.IntegerField(default=1)),
                ('bandwidth', models.IntegerField(default=1024)),
                ('cpu_units', models.IntegerField(default=1024)),
                ('cpu_limit', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('ipv6_ips', models.IntegerField(default=0)),
                ('ipv4_ips', models.IntegerField(default=0)),
                ('internal_ips', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ServiceBandwidth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandwidth', models.IntegerField(default=0)),
                ('bandwidth_banked', models.IntegerField(default=0)),
                ('bandwidth_stale', models.IntegerField(default=0)),
                ('system_tick', models.IntegerField(default=0)),
                ('renewal_dtm', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('lxc', 'LXC'), ('kvm', 'KVM')], default='lxc', max_length=255)),
                ('file', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=8)),
                ('ram', models.IntegerField(default=16)),
                ('swap', models.IntegerField(default=16)),
                ('cores', models.IntegerField(default=1)),
                ('bandwidth', models.IntegerField(default=1024)),
                ('cpu_units', models.IntegerField(default=1024)),
                ('cpu_limit', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('ipv6_ips', models.IntegerField(default=0)),
                ('ipv4_ips', models.IntegerField(default=0)),
                ('internal_ips', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('status', models.CharField(default='online', max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inveterate.cluster')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='IPPool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('ipv4', 'IPv4'), ('ipv6', 'IPv6')], default='ipv4', max_length=255)),
                ('network', models.GenericIPAddressField()),
                ('mask', models.IntegerField()),
                ('gateway', models.GenericIPAddressField()),
                ('internal', models.BooleanField(default=False)),
                ('interface', models.CharField(default='vmbr0', max_length=255)),
                ('dns', models.GenericIPAddressField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nodes', models.ManyToManyField(to='inveterate.node')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='NodeDisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('primary', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_disk', to='inveterate.node')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inveterate.node')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inveterate.plan')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('destroyed', 'Destroyed'), ('suspended', 'Suspended'), ('error', 'Error'), ('past_due', 'Past Due')], default='pending', max_length=255)),
                ('status_msg', models.CharField(blank=True, max_length=255, null=True)),
                ('hostname', models.CharField(max_length=255)),
                ('machine_id', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='inveterate.node')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inveterate.plan')),
                ('bandwidth', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service', to='inveterate.servicebandwidth')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('file', models.CharField(max_length=255, null=True)),
                ('primary', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disks', to='inveterate.service')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ServiceNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_id', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_network', to='inveterate.service')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.GenericIPAddressField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inveterate.ippool')),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inveterate.servicenetwork')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ServicePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=8)),
                ('ram', models.IntegerField(default=16)),
                ('swap', models.IntegerField(default=16)),
                ('cores', models.IntegerField(default=1)),
                ('bandwidth', models.IntegerField(default=1024)),
                ('cpu_units', models.IntegerField(default=1024)),
                ('cpu_limit', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('ipv6_ips', models.IntegerField(default=0)),
                ('ipv4_ips', models.IntegerField(default=0)),
                ('internal_ips', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('lxc', 'LXC'), ('kvm', 'KVM')], max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inveterate.nodedisk')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inveterate.template')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='service_plan',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service', to='inveterate.serviceplan'),
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stream', to='inveterate.service')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='VMMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('cpu_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('disk_usage', models.FloatField()),
                ('network_in', models.BigIntegerField()),
                ('network_out', models.BigIntegerField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='inveterate.service')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['service', 'timestamp'], name='inveterate__service_e3ba26_idx')],
            },
        ),
    ]
