# Generated by Django 5.2.2 on 2025-06-15 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inveterate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='maintenance_mode',
        ),
        migrations.RemoveField(
            model_name='node',
            name='status',
        ),
        migrations.DeleteModel(
            name='VMMetrics',
        ),
    ]
