# Generated by Django 5.2.11 on 2026-02-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inveterate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ippool',
            name='vlan_tag',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
