# Generated by Django 5.2.11 on 2026-02-23 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inveterate', '0002_ippool_vlan_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inveterate.node'),
        ),
        migrations.AddField(
            model_name='template',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='template',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('importing', 'Importing'), ('ready', 'Ready'), ('error', 'Error')], default='ready', max_length=32),
        ),
        migrations.AddField(
            model_name='template',
            name='status_msg',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='template',
            name='file',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
