# Generated by Django 5.2.11 on 2026-02-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inveterate', '0003_template_cloud_import'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('cloud_init', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='serviceplan',
            name='apps',
            field=models.ManyToManyField(blank=True, to='inveterate.appprofile'),
        ),
    ]
