# Generated by Django 5.2.11 on 2026-02-24 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inveterate', '0004_appprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('forward_port', models.IntegerField(default=80)),
                ('ssl', models.BooleanField(default=True)),
                ('force_ssl', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('npm_proxy_host_id', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_routes', to='inveterate.service')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PortGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('host', models.CharField(max_length=255)),
                ('admin_email', models.EmailField(max_length=254)),
                ('admin_password', models.CharField(max_length=255)),
                ('port_range_start', models.IntegerField(default=10000)),
                ('port_range_end', models.IntegerField(default=60000)),
                ('block_size', models.IntegerField(default=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pools', models.ManyToManyField(blank=True, to='inveterate.ippool')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PortBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_start', models.IntegerField()),
                ('port_end', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('service_network', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='port_block', to='inveterate.servicenetwork')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_blocks', to='inveterate.portgateway')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PortForward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_port', models.IntegerField()),
                ('internal_port', models.IntegerField()),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP'), ('both', 'TCP+UDP')], default='tcp', max_length=4)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('npm_stream_id', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('port_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwards', to='inveterate.portblock')),
            ],
            options={
                'ordering': ['-created'],
                'constraints': [models.UniqueConstraint(fields=('port_block', 'external_port', 'protocol'), name='unique_portblock_extport_proto')],
            },
        ),
        migrations.AddConstraint(
            model_name='portblock',
            constraint=models.UniqueConstraint(fields=('gateway', 'port_start'), name='unique_gateway_port_start'),
        ),
    ]
