# Generated by Django 6.0.2 on 2026-02-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inveterate', '0005_domainroute_portgateway_portblock_portforward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='bandwidth',
            field=models.IntegerField(default=0, help_text='Monthly bandwidth budget in GB (0 = unlimited)'),
        ),
    ]
