# Generated by Django 6.0.2 on 2026-02-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inveterate', '0006_cluster_bandwidth'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='annual_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
