# Generated by Django 6.0.2 on 2026-02-27 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inveterate', '0007_plan_annual_price_plan_monthly_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='appprofile',
            name='min_cores',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appprofile',
            name='min_disk',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appprofile',
            name='min_ram',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
