# Generated by Django 6.0.2 on 2026-02-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inveterate', '0008_appprofile_min_cores_appprofile_min_disk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='verify_ssl',
            field=models.BooleanField(default=False, help_text='Verify TLS certificates when connecting to the Proxmox API.'),
        ),
    ]
