# Generated by Django 6.0.2 on 2026-02-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inveterate', '0009_cluster_verify_ssl'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='servicenetwork',
            constraint=models.UniqueConstraint(fields=('service', 'net_id'), name='unique_service_net_id'),
        ),
    ]
