# Generated by Django 6.0.2 on 2026-03-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inveterate', '0010_servicenetwork_unique_service_net_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='username',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
