# Generated by Django 6.0.3 on 2026-03-10 22:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inveterate', '0013_encrypt_existing_credentials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(condition=models.Q(('machine_id__isnull', False)), fields=('machine_id', 'node'), name='unique_machine_id_per_node'),
        ),
    ]
