# Generated by Django 5.2.11 on 2026-07-05 16:05
# NOTE: hand-trimmed from an autogenerated migration that also picked up an
# unrelated, concurrently-developed `Service.operation_in_progress` field
# from another in-progress change to models.py. That field is NOT included
# here — it belongs in whatever migration the agent adding it creates.
# This migration only adds the `DispatchedTask` model (task_id -> owner
# mapping used by TaskStatusView to prevent cross-user task-status IDOR).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inveterate', '0014_unique_machine_id_per_node'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatched_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
