# Generated by Django 5.2.11 on 2026-07-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inveterate', '0015_dispatchedtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='operation_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
