# Generated by Django 5.2.11 on 2026-07-05 17:23

from django.db import migrations, models
from django.utils import timezone


def backfill_existing_routes_verified(apps, schema_editor):
    """Every route that already exists at deploy time is live and trusted.

    Without this, all production routes would drop to the new ``pending``
    default and get torn down on the next NPM sync. New routes created after
    deploy start at ``pending`` and must pass the TXT challenge.
    """
    DomainRoute = apps.get_model('inveterate', 'DomainRoute')
    DomainRoute.objects.all().update(
        verification_status='verified',
        verified_at=timezone.now(),
    )


def noop_reverse(apps, schema_editor):
    # Reverse is a no-op: the fields are dropped by the reversed AddField
    # operations, so there is nothing to undo here.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inveterate', '0016_service_operation_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainroute',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending verification'), ('verified', 'Verified'), ('failed', 'Verification failed')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='domainroute',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_existing_routes_verified, noop_reverse),
    ]
